### ISSUE TITLE
Flask app is not registered with this 'SQLAlchemy'

### ISSUE THREAD

**Issue by celi28** [edergernot/webnetworkdump#1]
Hello,
While trying to deploy, I got a HTTP error code 500.

**Related logs :**
```
webnetworkdump-app-1  | [2023-11-22 08:55:02,611] ERROR in app: Exception on / [GET]
webnetworkdump-app-1  | Traceback (most recent call last):
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
webnetworkdump-app-1  |     response = self.full_dispatch_request()
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
webnetworkdump-app-1  |     rv = self.handle_user_exception(e)
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
webnetworkdump-app-1  |     rv = self.dispatch_request()
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
webnetworkdump-app-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
webnetworkdump-app-1  |   File "/usr/src/app/WebNetdump.py", line 207, in index
webnetworkdump-app-1  |     content=get_status()
webnetworkdump-app-1  |   File "/usr/src/app/WebNetdump.py", line 69, in get_status
webnetworkdump-app-1  |     "networkdevices":len(network_device.query.all())}
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2693, in all
webnetworkdump-app-1  |     return self._iter().all()  # type: ignore
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2847, in _iter
webnetworkdump-app-1  |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2308, in execute
webnetworkdump-app-1  |     return self._execute_internal(
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2178, in _execute_internal
webnetworkdump-app-1  |     bind = self.get_bind(**bind_arguments)
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/session.py", line 53, in get_bind
webnetworkdump-app-1  |     engines = self._db.engines
webnetworkdump-app-1  |   File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 690, in engines
webnetworkdump-app-1  |     raise RuntimeError(
webnetworkdump-app-1  | RuntimeError: The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
webnetworkdump-app-1  | 172.21.0.1 - - [22/Nov/2023 08:55:02] "GET / HTTP/1.1" 500 -
``` 

I seem that `RUN python create_db.py` does not initialize the database. `dump_db.sqlite3` doesn't seem to exist on the docker image.

**Environment :**
```
17959% docker -v
Docker version 24.0.6, build ed223bc
17959% docker-compose -v
Docker Compose version v2.23.0-desktop.1
```

**Comment by edergernot** [comment]
Hi, many thanks for being interested in my project. This Project isn't in developement anymore because I splittet it in 2 parts, and removed sql. You can checkout: https://github.com/edergernot/WebNetworkDump1.1 for discovering and https://github.com/edergernot/WebNetworkgraph for parsing and drawing.
Kind Regards
Gernot
